### ISSUE TITLE
Please select a zip file

### ISSUE THREAD

**Issue by KonusanSincap** [KayleeWilliams/Discord-Data-Explorer#1]
![image](https://user-images.githubusercontent.com/36803128/222351282-f9833bb8-0b2f-4deb-9724-318b726221d5.png)

Please fix.

**Comment by KayleeWilliams** [comment]
Hey, 
It should be working now if you pull the latest version.
Let me know if it works for you.

**Comment by KonusanSincap** [comment]
Yes the zip problem is solved thanks but now there is another problem
![image](https://user-images.githubusercontent.com/36803128/222747542-00d2e5be-b36b-4976-94ef-5e64e01e660e.png)

**Comment by KayleeWilliams** [comment]
> Yes the zip problem is solved thanks but now there is another problem ![image](https://user-images.githubusercontent.com/36803128/222747542-00d2e5be-b36b-4976-94ef-5e64e01e660e.png)

Think the problem should be solved now.

**Comment by KonusanSincap** [comment]
Yes all problems fixed thanks.
